"""The base class every database model inherits from.

Two things happen here that matter later:

1. A naming convention for indexes and constraints. Without it, Postgres invents
   names and Alembic autogenerate produces noisy, unstable migrations. With it,
   every constraint has a predictable name we can reference in a downgrade.

2. Shared mixins for the id and timestamp columns, so every table is consistent.
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, MetaData, func, text
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# %(table_name)s and friends are filled in by SQLAlchemy.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class UUIDPrimaryKey:
    """UUID primary keys, generated by Postgres itself.

    Why UUID and not an auto-incrementing integer: ids are exposed in URLs, and
    sequential integers would let anyone enumerate other students' rooms. The
    default is server-side (gen_random_uuid, built into Postgres 13+) so a row
    inserted by a raw SQL script still gets a valid id.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


class CreatedAtMixin:
    """Adds `created_at`.

    Filled by Postgres with now(), which is the time the *transaction* started,
    not wall clock. Always timezone-aware. A naive timestamp becomes ambiguous the moment
    anything runs in another timezone, and the study-history endpoint filters on
    this column.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )


class UpdatedAtMixin:
    """Adds `updated_at`, for rows that are edited after they are created.

    Only for genuinely mutable entities — a room being archived, a student being
    renamed. Event records such as turns and attempts should not use it: they
    already carry precise lifecycle columns (`completed_at`, `finished_at`) and
    `updated_at` would state the same fact less clearly.
    """

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )
